### PR TITLE
Ratified Status Change

### PR DESCRIPTION
**Pull request by TelegramSam**
Signed-off-by: Sam Curren <telegramsam@gmail.com>

### CODE REVIEW

**Comment by TelegramSam** [comment]
The DIF Steering Committee approved our status change to DIF Ratified Specification during the July 7th SC Meeting. This PR reflects that change.

**Comment by dhh1128** [comment]
I don't have any power to assign myself to review or merge or similar -- but I just wanted to leave my note of approval and enthusiasm that this be merged asap.

**Comment by 2byrds** [comment]
Great news! Congrats everyone. It was awesome to witness your work/effort. Bravo!

**Comment by mccown** [comment]
Approved in the DIDcomm WG call on 07112022.

**Pull request merged**
