### PR TITLE
Attachment Format Attribute

### PR DESCRIPTION
**Pull request by TelegramSam**
Signed-off-by: Sam Curren <telegramsam@gmail.com>

### CODE REVIEW

**Review by kdenhartog — COMMENTED** [review]
Is this mainly for instances where things get base64 encoded and stuff like that?

**Comment by TelegramSam** [comment]
The main reason was knowing what the contents are besides json, etc. json, but which json? In the Aries Cred exchange protocols, there was an additional attribute used to indicate the format of the credential outside of the attachment. This is an attempt to make this more clear.

**Review by kdenhartog — APPROVED** [review]
Makes sense to me now. Thanks for clarifying it's purpose.

**Comment by tplooker** [comment]
Discussed on 28th June WG call resolved to merge

**Pull request merged**
