### PR TITLE
remove conflict with issue #351

### PR DESCRIPTION
**Pull request by dhh1128**
Signed-off-by: dhh1128 <daniel.hardman@gmail.com>

### CODE REVIEW

**Comment by TelegramSam** [comment]
This is a small but important change. Removing this allows for future work without conflict. I vote merge.

**Comment by dhh1128** [comment]
I added one more change. I think with this additional change, this PR fixes #351 (although it doesn't fully resolve @TimoGlastra 's issue; it just lets it be fixed somewhere other than this spec).

**Comment by dhh1128** [comment]
fixed #351

**Review by TimoGlastra — APPROVED** [review]
LGTM!

**Pull request merged**
