### PR TITLE
First cut at i18 section

### PR DESCRIPTION
**Pull request by dhh1128**
Signed-off-by: Daniel Hardman <daniel.hardman@sicpa.com>

This content is not ready to merge, because the new file isn't referenced in the spec.js file anywhere. I wanted to see if we agreed on the ideas before inserting them somewhere.

### CODE REVIEW

**Comment by dhh1128** [comment]
Fixes #226

**Comment by dhh1128** [comment]
Remove inline.
Define error code for "Can't read that language. Can you send me this other one? `<lang code>`"
Define how to use Feature Discovery to find out the lang of the other party.
Make `lang` setting sticky.

**Review by kdenhartog — APPROVED** [review]
I'm liking where this is going

**Comment by TelegramSam** [comment]
I like this. I have a minor preference to introduce the `lang` header first, and then the `accept-lang`, but  that is a super minor point.

I love that you included the inline mode as an extension. This preserves the thinking and work, but does not require it, lowering adoption hurdles.

I think this is ready to merge.

**Comment by awoie** [comment]
As per WG meeting from August 2nd, merging this PR

**Pull request merged**
