### PR TITLE
Removed processing model section

### PR DESCRIPTION
**Pull request by awoie**
Proposal on removing the processing model section since it just repeats what is described in the other intro sections without detailing the particular items. Intention is just to make the spec simpler. If people insist on that section, we can drop the PR.

### CODE REVIEW

**Review by kdenhartog — APPROVED** [review]
+1 to this

**Review by TelegramSam — APPROVED** [review]

**Review by kdenhartog — APPROVED** [review]

**Review by dhh1128 — APPROVED** [review]

**Comment by TelegramSam** [comment]
@awoie can you resolve conflicts?

**Comment by awoie** [comment]
> @awoie can you resolve conflicts?

done

**Comment by awoie** [comment]
Merging as per 6 September WG meeting.

**Pull request merged**
