### PR TITLE
Proposed reply header text

### PR DESCRIPTION
**Pull request by TelegramSam**
In our WG meeting, we decided to propose text for reply header handling. This is that proposal.

I am not advocating specifically for this: it is my intent to explore what is required to allow reply processing, including evaluating the carrying costs of this approach. Everything in this PR is subject to change/improvement/refinement. 

Relates to #134

### CODE REVIEW

**Comment by TelegramSam** [comment]
In WG Call 01042021 we discussed a possible alternative: What if the endpoint was expressed as an 'endpoint_override' instead of as the 'reply' method included in this PR? Could that eliminate some of the shortcomings?

**Comment by llorllale** [comment]
This path deviates away from the approach advocated for in DIDComm v1 a couple of weeks back which was to use a single identifier to convey the necessary parameters for the recipient to reply. It was argued back then that such an approach would essentially build a bridge into V2.

That conversation took place a week or two before this PR was pushed. Is this PR still the current thinking or have we switched away from this and on to the direction I refer to above?

**Comment by TelegramSam** [comment]
I propose we kill this PR. Let's discuss in WG meeting today.

**Comment by TelegramSam** [comment]
Killed per conversation in WG 20210614

**Pull request closed without merging**
