### PR TITLE
potentially fixes #257; made serviceEndpoint an URI or object

### LINKED ISSUE #257: Allow for objects as serviceEndpoints
According to DID Core, objects (set/map) are possible too. The current DIDComm v2 spec only allows URIs for service endpoints but we should rather let the specific transport decide what form the `serviceEndpoint` should have. 

Background: we are working on a transport that will likely require an object rather than a URI.

### PR DESCRIPTION
**Pull request by awoie**
potentially fixes #257; made serviceEndpoint an URI or object

### CODE REVIEW

**Review by kdenhartog — APPROVED** [review]

**Comment by awoie** [comment]
Before we can merge, we should change the language. The WG was fine with the changes in general but requested to use the same language as in DID Core. Furthermore, in case the serviceEndpoint is a map, we should require an additional `transportType` property (URI) to indicate the actual transport. Note, for URIs, the type of transport can be usually derived from the URI scheme.

**Comment by TelegramSam** [comment]
discussed changes that point to the DID Core spec.

**Comment by TelegramSam** [comment]
Discussed WG 20220314. 

Discussed ION, which impl cannot accept the args as we've designed.
Suggestion to test the proposed object format to make sure it works.
related: https://github.com/decentralized-identity/didcomm-messaging/issues/294

general consensus was that making the adjustment might be easier than getting ION to fully support the did core spec as written. ION support is desired, either by contacting their team or by making the object adjustment.

We support moving AWAY from a string and to the full object support to avoid having two forms to parse. Need a PR with all of those changes to continue the discussion.

**Comment by jayv80** [comment]
@TelegramSam I've checked today with my team and the Hedera identity fabric that we currently manage. We have the same problem as ION at the moment. 
We can only extend the ServiceEndpoint with the current implementation of the DID-Core spec. Meaning the ServiceEndpoint can be an object that contains specific attributes. 

This design choice was made due to the fact that is more logical to include specific attributes in the ServiceEndpoint ojbect, than sibling attributes in the Services property. 
Because, it could happen that during further extensions of the DID-Core specification, sibling attributes are in collision with each other.  

So this problem is not limited to ION alone. I honestly thing that we're not changing the current DID-Core implementation for Hedera in the short future.

**Comment by TelegramSam** [comment]
> Because, it could happen that during further extensions of the DID-Core specification, sibling attributes are in collision with each other.

Given how few service endpoints there are, and DIDComm being a majority force I think it's unlikely that they would choose a colliding attribute. That said, knowing that you've made the same choice as ION is good input for our efforts.

**Comment by TelegramSam** [comment]
Now irrellevant, fixed in PR #352

**Pull request closed without merging**
